-- @file Assigns gui arguments for syntax and 🖌️ highlight groups
-- @author Reuben L. Lillie <https://zirk.us/@reubenlillie>
-- @since 0.1.0
-- @since 1.0.0 Reformat module to return a local table
--              Deprecate local function setup()
--              Add M.load()

-- Declare a local table to return public module functions
local M = {}

-- Defines 🖌️ highlight groups
function M.load(settings)
  local p = settings.palette

  return {
    -- :help group-name
    Comment = {fg = p.lightGray},
    Constant = {fg = p.yellow},
    Identifier = {fg = p.blue},
    Statement = {fg = p.red},
    PreProc = {fg = p.purple},
    Type = {fg = p.green},
    Special = {fg = p.pink},
    Underlined = {underline = true},
    Ignore = {fg = p.darkGray, bg = p.lightGray, italic = true},
    Error = {fg = p.darkGray, bg = p.red},
    Todo = {fg = p.darkGray, bg = p.blue},

    -- :help highlight-groups
    ColorColumn = {reverse = true},
    Conceal = {fg = p.lightGray},
    CurSearch = {fg = p.darkGray, bg = p.green, bold = true},
    Cursor = {reverse = true},
    lCursor = {link = 'Cursor'},
    CursorIM = {link = 'Cursor'},
    CursorColumn = {link = 'CursorLine'},
    CursorLine = {fg = 'NONE', bg = p.black},
    Directory = {link = 'Identifier'},
    DiffAdd = {fg = p.green},
    DiffChange = {fg = p.yellow},
    DiffDelete = {fg = p.red},
    DiffText = {fg = p.lightGray},
    EndOfBuffer = {link = 'Comment'},
    ErrorMsg = {link = 'Error'},
    WinSeparator = {link = 'Ignore'},
    Folded = {link = 'Ignore'},
    FoldColumn = {link = 'Folded'},
    SignColumn = {link = 'Normal'},
    IncSearch = {fg = p.darkGray, bg = p.yellow, bold = true},
    Substitute = {link = 'Sign'},
    LineNr = {fg = p.white, bg = p.black, bold = true},
    LineNrAbove = {link = 'Comment'},
    LineNrBelow = {link = 'LineNrAbove'},
    CursorLineNr = {link = 'LineNr'},
    CursorLineFold = {link = 'Folded'},
    CursorLineSign = {link = 'SignColumn'},
    MatchParen = {reverse = true},
    ModeMsg = {fg = p.white},
    MsgArea = {fg = p.white},
    MsgSeparator = {fg = p.white},
    MoreMsg = {fg = p.white},
    NonText = {fg = p.white},
    Normal = {fg = p.white, bg = p.darkGray},
    Pmenu = {link = 'CursorLine'},
    PmenuSel = {reverse = true, bold = true},
    PmenuSbar = {link = 'CursorLine'},
    PmenuThumb = {bg = p.yellow},
    PopupNotification = {link = 'Normal'},
    Question = {link = 'MoreMsg'},
    QuickFixLine = {link = 'CursorLine'},
    Search = {link = 'IncSearch'},
    SpecialKey = {link = 'Special', bold = true, italic = true},
    SpellBad = {fg = p.red, underline = true},
    SpellCap = {link = 'SpellBad'},
    SpellLocal = {link = 'SpellBad'},
    SpellRare = {link = 'SpellBad'},
    StatusLine = {reverse = true, bold = true},
    StatusLineNC = {link = 'Ignore'},
    TabLine = {link = 'Ignore'},
    TabLineFill = {link = 'Normal'},
    TabLineSel = {link = 'Normal'},
    Title = {link = 'Normal'},
    Visual = {link = 'CursorLine'},
    VisualNOS = {link = 'Visual'},
    WarningMsg = {fg = p.darkGray, bg = p.yellow},
    Whitespace = {link = 'PreProc', italic = true},
    WildMenu = {fg = p.darkGray, bg = p.green},
    WinBar = {link = 'Normal'},
    WinBarNC = {link = 'Comment'},
    Menu = {link = 'CursorLine'},
    Scrollbar = {link = 'PmenuSbar'},
    Tooltip = {link = 'CursorLine'},

    -- HTML
    htmlArg = {link = 'Type'},
    htmlBold = {bold = true},
    htmlEndTag = {link = 'htmlTag'},
    htmlH1 = {link = 'htmlBold'},
    htmlH2 = {link = 'htmlH1'},
    htmlH3 = {link = 'htmlH1'},
    htmlH4 = {link = 'htmlH1'},
    htmlH5 = {link = 'htmlH1'},
    htmlH6 = {link = 'htmlH1'},
    htmlItalic = {italic = true},
    htmlLink = {underline = true},
    htmlSpecialChar = {link = 'Special'},
    htmlSpecialTagName = {link = 'Statement'},
    htmlTag = {fg = p.white, bg = 'NONE'},
    htmlTagN = {link = 'Statement'},
    htmlTagName = {link = 'Statement'},
    htmlTitle = {link = 'Special'},

    -- Markdown
    markdownCodeBlock = {link = 'Type'},
    markdownCodeDelimiter = {link = 'Type'},
    markdownH1 = {link = 'htmlBold'},
    markdownH1Delimiter = {link = 'Identifier'},
    markdownH2 = {link = 'htmlH1'},
    markdownH2Delimiter = {link = 'markdownH1Delimiter'},
    markdownH3 = {link = 'htmlH1'},
    markdownH3Delimiter = {link = 'markdownH1Delimiter'},
    markdownH4 = {link = 'htmlH1'},
    markdownH4Delimiter = {link = 'markdownH1Delimiter'},
    markdownH5 = {link = 'htmlH1'},
    markdownH5Delimiter = {link = 'markdownH1Delimiter'},
    markdownH6 = {link = 'htmlH1'},
    markdownH6Delimiter = {link = 'markdownH1Delimiter'},
    markdownYamlHead = {link = 'Normal'},

    -- YAML
    yamlBlockMappingKey = {link = 'Constant'},
    yamlDocumentStart = {link = 'Normal'},
    yamlFlowIndicator = {link = 'Normal'},
    yamlFlowString = {link = 'Type'},
    yamlKeyValueDelimiter = {link = 'Normal'},

    -- CSS
    cssAtKeyword = {link = 'Special'},
    cssBraces = {link = 'Comment'},

    -- JavaScript
    javaScriptBoolean = {link = 'Special'},
    javaScriptBraces = {link = 'PreProc'},
    javaScriptConditional = {link = 'Constant'},
    javaScriptConstant = {link = 'Statement'},
    javaScriptEmbed = {fg = p.white, bold = true},
    javaScriptException = {link = 'Statement'},
    javaScriptGlobal = {link = 'Constant'},
    javaScriptLabel = {link = 'Statement'},
    javaScriptMember = {link = 'Constant'},
    javaScriptNull = {link = 'Special'},
    javaScriptNumber = {link = 'Identifier'},
    javaScriptOperator = {link = 'Identifier'},
    javaScriptParens = {link = 'PreProc'},
    javaScriptRepeat = {link = 'Statement'},
    javaScriptReserved = {link = 'Special'},
    javaScriptSpecial = {link = 'Type'},
    javaScriptStatement = {link = 'Constant'},
    javaScriptStringD = {link = 'Type'},
    javaScriptStringS = {link = 'Type'},
    javaScriptStringT = {link = 'Type'},

    -- NvimTree
    NvimTreeCursorLine = {link = 'CursorLine'},
    NvimTreeEmptyFolderName = {link = 'Comment'},
    NvimTreeEndOfBuffer = {link = 'EndOfBuffer'},
    NvimTreeFolderIcon = {fg = p.blue},
    NvimTreeFolderName = {fg = p.blue},
    NvimTreeGitDirty = {fg = p.red},
    NvimTreeGitNew = {fg = p.yellow},
    NvimTreeImageFile = {link = 'Special'},
    NvimTreeIn = {bg = p.green},
    NvimTreeIndentMarker = {fg = p.lightGray},
    NvimTreeNormal = {link = 'Normal'},
    NvimTreeOpenedFolderName = {fg = p.blue, italic = true},
    NvimTreeRootFolder = {fg = p.white, bold = true},
    NvimTreeSpecialFile = {link = 'Special', underline = true},
    NvimTreeVertSplit = {link = 'Comment'},
  }
end

return M
